add main logo and some icons
yaboiishere/not_spotfiy pull request #15
Opened 2023-05-16 06:09 UTC by kikiom

2023-05-16 07:55 UTC, yaboiishere requested changes

2023-05-16 07:55 UTC, yaboiishere commented on lib/not_spotify_web/components/layouts/live.html.heex
> +            <svg
Тези икони от FontAwesome ли са? Ако са направи ги с `<FontAwesome.LiveView.icon name="gear" type="solid" class="h-5 w-5" />`. Направи ги да са с размери 5 на 5, оранжеви и като се сложи мишката върху тях да стават по-тъмно оранжеви. Може да видиш на 39 и 37 ред има примери. Update-нах ти клона с най-новата версия на main. Трябва да git pull-неш

2023-05-16 07:55 UTC, yaboiishere commented on lib/not_spotify_web/components/layouts/live.html.heex
> +          <svg
Може да добавим имато някъде понеже заема твърде малко място. Трябва да питаме @JustSTICC

2023-05-17 05:13 UTC, JustSTICC approved these changes
shpek

2023-05-19 13:11 UTC, yaboiishere commented on lib/not_spotify_web/components/layouts/live.html.heex
> +          <svg
Това може да го върнем както си беше с img в друг бранч смених този logo.svg с нашия

2023-05-19 16:03 UTC, JustSTICC approved these changes
OwO

2023-05-20 18:43 UTC, yaboiishere approved these changes

2023-05-20 18:43 UTC, merged